version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker CLI and Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build . -t $ARTIFACTORY_URL/cvm-toolkit-docker-local/toolkit:$CIRCLE_SHA1 -t $ARTIFACTORY_URL/cvm-toolkit-docker-local/toolkit:latest \
                          -t $DOCKERHUB_USERNAME/toolkit:$CIRCLE_SHA1 -t $DOCKERHUB_USERNAME/toolkit:latest
      - run:
          name: Authenticate with Artifactory
          command: |
            docker login $ARTIFACTORY_URL -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_TOKEN
      - run:
          name: Push Docker Image to Artifactory
          command: |
            docker push $ARTIFACTORY_URL/cvm-toolkit-docker-local/toolkit:latest
            docker push $ARTIFACTORY_URL/cvm-toolkit-docker-local/toolkit:$CIRCLE_SHA1
      - run:
          name: Authenticate with Dockerhub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker Image to Dockerhub
          command: |
            docker push kennasecurity/toolkit:latest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
           context: 
            - devhub-artifactory
            - dockerhub
           filters:
            branches:
              only:
                - main
                - cmans/dockerhub